SELECT DISTINCT
    ZWACHATSESSION.Z_PK,
    ZWACHATSESSION.ZPARTNERNAME,
    ZWACHATSESSION.ZLASTMESSAGEDATE,
    ZWACHATSESSION.ZCONTACTJID
  FROM
    ZWACHATSESSION
  WHERE
    ZWACHATSESSION.ZHIDDEN = 0
  AND
    ZWACHATSESSION.ZETAG IS NOT NULL
  ORDER BY
    ZWACHATSESSION.ZLASTMESSAGEDATE DESC